import Link from "next/link";
import { getWhatsAppHref } from "@/constants/contact";
import { Container } from "@/components/ui/Container";
import { TrackedLink } from "@/components/ui/TrackedLink";

export function FinalCtaSection({ locale = "es" }: { locale?: "en" | "es" }) {
  const copy = locale === "en" ? { eyebrow: "Let's talk", title: "Do you have an idea or a process that could work better?", description: "Tell me what you need and we can explore the best way to turn it into a digital solution.", cta: "Tell me about your project", whatsapp: "Write on WhatsApp" } : { eyebrow: "Hablemos", title: "¿Tenés una idea o un proceso que podría funcionar mejor?", description: "Contame qué necesitás y podemos analizar juntos la mejor forma de convertirlo en una solución digital.", cta: "Contame tu proyecto", whatsapp: "Escribime por WhatsApp" };
  const whatsappHref = getWhatsAppHref(locale);

  return <section className="py-20 sm:py-28"><Container><div className="relative overflow-hidden rounded-3xl bg-ink px-6 py-14 sm:px-12 sm:py-16"><div className="cta-grid pointer-events-none absolute inset-0 opacity-70" /><div className="pointer-events-none absolute -right-16 -top-20 h-64 w-64 rounded-full border border-white/10 motion-cta-orbit" /><div className="pointer-events-none absolute -right-2 top-4 h-36 w-36 rounded-full border border-white/10" /><div className="relative max-w-2xl"><p className="text-sm font-semibold uppercase tracking-[0.16em] text-[#75c7bb]">{copy.eyebrow}</p><h2 className="mt-4 text-3xl font-semibold tracking-[-0.04em] text-white sm:text-4xl">{copy.title}</h2><p className="mt-5 max-w-xl text-base leading-7 text-white/65">{copy.description}</p><div className="mt-8 flex flex-col gap-3 sm:flex-row"><Link href={`/${locale}/contacto`} className="group inline-flex items-center justify-center rounded-full bg-[#eaf4f1] px-6 py-3.5 text-sm font-semibold text-[#071512] transition-[background-color,transform] duration-300 hover:-translate-y-0.5 hover:bg-[#70d1bf]">{copy.cta} <span className="ml-2 transition-transform duration-300 group-hover:translate-x-1" aria-hidden="true">→</span></Link>{whatsappHref && <TrackedLink href={whatsappHref} external eventName="click_whatsapp" target="_blank" rel="noreferrer" className="inline-flex items-center justify-center rounded-full border border-white/20 px-6 py-3.5 text-sm font-semibold text-white transition-[background-color,border-color,transform] duration-300 hover:-translate-y-0.5 hover:border-[#70d1bf] hover:bg-white/10">{copy.whatsapp} <span className="ml-2" aria-hidden="true">↗</span></TrackedLink>}</div></div></div></Container></section>;
}
