import Link from "next/link";
import { Container } from "@/components/ui/Container";
import { TrackedLink } from "@/components/ui/TrackedLink";

export function HeroSection({ locale = "es" }: { locale?: "en" | "es" }) {
  const copy = locale === "en" ? { eyebrow: "TAILORED SOFTWARE DEVELOPMENT", title: "I turn ideas into digital solutions.", description: "I build websites, applications, and custom software that help professionals and businesses digitize processes, sell more, and work more efficiently.", cta: "Tell me about your project", projects: "View projects", status: "Idea in motion", statusDetail: "Simple · Scalable" } : { eyebrow: "DESARROLLO DE SOFTWARE A MEDIDA", title: "Transformo ideas en soluciones digitales.", description: "Desarrollo páginas web, aplicaciones y sistemas a medida que ayudan a profesionales y empresas a digitalizar procesos, vender más y trabajar de forma más eficiente.", cta: "Contame tu proyecto", projects: "Ver proyectos", status: "Idea en marcha", statusDetail: "Simple · Escalable" };
  return <section className="relative overflow-hidden border-b border-line"><div className="pointer-events-none absolute -right-24 top-12 h-64 w-64 rounded-full bg-[#163a35] blur-3xl motion-soft-pulse" /><Container className="relative grid items-center gap-12 py-16 sm:gap-14 sm:py-20 lg:grid-cols-[1.08fr_0.92fr] lg:gap-10 lg:py-20"><div className="relative z-10 motion-rise-in"><p className="mb-5 text-sm font-semibold uppercase tracking-[0.16em] text-accent">{copy.eyebrow}</p><h1 className="max-w-2xl text-[2.75rem] font-semibold leading-[1.08] tracking-[-0.05em] text-ink sm:text-6xl lg:text-[4.25rem]">{copy.title}</h1><p className="mt-6 max-w-xl text-lg leading-8 text-muted">{copy.description}</p><div className="mt-8 flex flex-col gap-3 sm:flex-row"><TrackedLink href={`/${locale}/contacto`} eventName="click_contact_hero" className="group inline-flex items-center justify-center rounded-full bg-accent px-6 py-3.5 text-sm font-semibold text-[#071512] transition-[background-color,transform,box-shadow] duration-300 hover:-translate-y-0.5 hover:bg-[#70d1bf] hover:shadow-lg hover:shadow-accent/15">{copy.cta} <span className="ml-2 transition-transform duration-300 group-hover:translate-x-1" aria-hidden="true">→</span></TrackedLink><Link href={`/${locale}/proyectos`} className="group inline-flex items-center justify-center rounded-full border border-line px-6 py-3.5 text-sm font-semibold text-ink transition-[border-color,background-color,transform] duration-300 hover:-translate-y-0.5 hover:border-accent hover:bg-surface">{copy.projects} <span className="ml-2 transition-transform duration-300 group-hover:translate-x-1" aria-hidden="true">→</span></Link></div></div><HeroVisual status={copy.status} statusDetail={copy.statusDetail} /></Container></section>;
}

function HeroVisual({ status, statusDetail }: { status: string; statusDetail: string }) {
  return <div className="relative mx-auto w-full max-w-[400px] motion-hero-float lg:max-w-[420px]" aria-label="Abstract digital solution dashboard" role="img"><div className="absolute -left-7 top-12 h-28 w-28 rounded-full bg-[#163a35] blur-2xl motion-soft-pulse" /><div className="relative rounded-3xl border border-line bg-white p-3 shadow-soft transition-transform duration-500 hover:-translate-y-1"><div className="relative overflow-hidden rounded-2xl bg-ink p-5 sm:p-7"><div className="relative flex items-center justify-between"><div className="flex gap-1.5"><span className="h-2 w-2 rounded-full bg-white/35" /><span className="h-2 w-2 rounded-full bg-white/35" /><span className="h-2 w-2 rounded-full bg-white/35" /></div><span className="flex items-center gap-1.5 rounded-full bg-white/10 px-3 py-1 text-[10px] text-white/55"><span className="h-1.5 w-1.5 rounded-full bg-[#75c7bb]" />overview</span></div><div className="relative mt-10 grid grid-cols-[0.72fr_1fr] gap-3"><div className="space-y-3"><div className="h-2 w-16 rounded-full bg-white/20" /><div className="h-2 w-24 rounded-full bg-white/10" /><div className="h-24 rounded-xl border border-white/10 bg-white/5" /></div><div className="rounded-xl border border-white/10 bg-white/5 p-4"><div className="flex items-end gap-2"><span className="h-14 w-3 rounded-t bg-[#75c7bb]" /><span className="h-20 w-3 rounded-t bg-[#4aa59a]" /><span className="h-10 w-3 rounded-t bg-white/30" /><span className="h-24 w-3 rounded-t bg-[#75c7bb]" /><span className="h-16 w-3 rounded-t bg-white/30" /></div><div className="mt-4 h-2 w-20 rounded-full bg-white/15" /></div></div><div className="mt-3 grid grid-cols-3 gap-3"><div className="h-16 rounded-xl bg-[#16302e]" /><div className="h-16 rounded-xl bg-[#1d2b31]" /><div className="h-16 rounded-xl bg-[#183633]" /></div></div><div className="absolute -bottom-5 -right-4 rounded-2xl border border-line bg-white px-4 py-3 shadow-soft motion-status-float sm:-right-8"><div className="flex items-center gap-3"><span className="flex h-8 w-8 items-center justify-center rounded-full bg-[#163a35] text-accent">✓</span><div><p className="text-xs font-semibold text-ink">{status}</p><p className="mt-0.5 text-[11px] text-muted">{statusDetail}</p></div></div></div></div></div>;
}
