import Link from "next/link";
import { Container } from "@/components/ui/Container";

export function HeroSection() {
  return <section className="overflow-hidden border-b border-line"><Container className="relative grid items-center gap-12 py-16 sm:gap-14 sm:py-20 lg:grid-cols-[1.08fr_0.92fr] lg:gap-10 lg:py-20"><div className="relative z-10"><p className="mb-5 text-sm font-semibold uppercase tracking-[0.16em] text-accent">DESARROLLO DE SOFTWARE A MEDIDA</p><h1 className="max-w-2xl text-[2.75rem] font-semibold leading-[1.08] tracking-[-0.05em] text-ink sm:text-6xl lg:text-[4.25rem]">Transformo ideas en soluciones digitales.</h1><p className="mt-6 max-w-xl text-lg leading-8 text-muted">Desarrollo páginas web, aplicaciones y sistemas a medida que ayudan a profesionales y empresas a digitalizar procesos, vender más y trabajar de forma más eficiente.</p><div className="mt-8 flex flex-col gap-3 sm:flex-row"><Link href="/contacto" className="inline-flex items-center justify-center rounded-full bg-ink px-6 py-3.5 text-sm font-semibold text-white transition-colors hover:bg-accent">Contame tu proyecto <span className="ml-2" aria-hidden="true">→</span></Link><Link href="/proyectos" className="inline-flex items-center justify-center rounded-full border border-line px-6 py-3.5 text-sm font-semibold text-ink transition-colors hover:border-ink">Ver proyectos</Link></div></div><HeroVisual /></Container></section>;
}

function HeroVisual() {
  return <div className="relative mx-auto w-full max-w-[400px] lg:max-w-[420px]" aria-label="Panel abstracto de una solución digital" role="img"><div className="absolute -left-7 top-12 h-28 w-28 rounded-full bg-[#eaf3f1] blur-2xl" /><div className="relative rounded-3xl border border-line bg-white p-3 shadow-soft"><div className="rounded-2xl bg-ink p-5 sm:p-7"><div className="flex items-center justify-between"><div className="flex gap-1.5"><span className="h-2 w-2 rounded-full bg-white/35" /><span className="h-2 w-2 rounded-full bg-white/35" /><span className="h-2 w-2 rounded-full bg-white/35" /></div><span className="rounded-full bg-white/10 px-3 py-1 text-[10px] text-white/55">overview</span></div><div className="mt-10 grid grid-cols-[0.72fr_1fr] gap-3"><div className="space-y-3"><div className="h-2 w-16 rounded-full bg-white/20" /><div className="h-2 w-24 rounded-full bg-white/10" /><div className="h-24 rounded-xl border border-white/10 bg-white/5" /></div><div className="rounded-xl border border-white/10 bg-white/5 p-4"><div className="flex items-end gap-2"><span className="h-14 w-3 rounded-t bg-[#75c7bb]" /><span className="h-20 w-3 rounded-t bg-[#4aa59a]" /><span className="h-10 w-3 rounded-t bg-white/30" /><span className="h-24 w-3 rounded-t bg-[#75c7bb]" /><span className="h-16 w-3 rounded-t bg-white/30" /></div><div className="mt-4 h-2 w-20 rounded-full bg-white/15" /></div></div></div><div className="mt-3 grid grid-cols-3 gap-3"><div className="h-16 rounded-xl bg-[#eef5f3]" /><div className="h-16 rounded-xl bg-[#f3f5f6]" /><div className="h-16 rounded-xl bg-[#e3efed]" /></div></div><div className="absolute -bottom-5 -right-4 rounded-2xl border border-line bg-white px-4 py-3 shadow-soft sm:-right-8"><div className="flex items-center gap-3"><span className="flex h-8 w-8 items-center justify-center rounded-full bg-[#eaf3f1] text-accent">✓</span><div><p className="text-xs font-semibold text-ink">Idea en marcha</p><p className="mt-0.5 text-[11px] text-muted">Simple · Escalable</p></div></div></div></div>;
}
